### ISSUE TITLE
Multiple dispatchs making store to act weird

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.Livechat#100]
Dispatch several "actions" at the same time seems to update the store incorrectly.
It probably picks the same `prevState` for most dispatchs and then sets an outdated state.

I've encountered this issue on #97 (it shouldn't be merged until this is solved).
In a server with the setting `showConnecting: true`, when an agent take a client, the composer must hide `Connecting to agent`.
Here's where the issue happens in this case: https://github.com/RocketChat/Rocket.Chat.Livechat/blob/master/src/lib/main.js#L103
```jsx
SDK.onMessage((message) => {
	store.setState({ messages: insert(store.state.messages, message).filter(({ msg, attachments }) => ({ msg, attachments })) });
	onNewMessage(message);
	doPlaySound(message);
});
```

This should happen when a message is received:
1. the message is inserted on the store
2. onNewMessage is called and  sets `connecting: false`.
3. doPlaySound is called and sets sound on the store.

What happens is:
1. message is set
2. connecting is set
3. sound is set, but picks a wrong state and sets previous version of connecting.

---
The same issue happens on alerts.
If there's several alerts to be dismissed automatically at the same time like this:
```
const alerts = [
	{ id: 1, children: 'Success alert', success: true, timeout: 1000 },
	{ id: 2, children: 'Warning alert', warning: true, timeout: 1000 },
	{ id: 3, children: 'Error alert', error: true, timeout: 1000 },
	{ id: 4, children: 'Custom colored alert', color: '#000', timeout: 1000 },
];
```
One alert will remain on the screen.

**Comment by tassoevan** [comment]
`store.setState()` is asynchronous just to support an asynchronous reducer. Since we're not using reducers at all for now, maybe we should make it synchronous.

**Comment by tassoevan** [comment]
Why not?

```js
SDK.onMessage(async(message) => {
	await store.setState({ messages: insert(store.state.messages, message).filter(({ msg, attachments }) => ({ msg, attachments })) });
	await onNewMessage(message);
	await doPlaySound(message);
});
```

**Comment by diegolmello** [comment]
@tassoevan Oh, I didn't know our `setState` is asynchronous.
Your sample works. Thanks!

I'm afraid async/await don't work for the multiple alerts case.
It could be done in a singleton Alert class, but it seems to me it's a job to be done by the store itself.
