### ISSUE TITLE
Header Alert component

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.Livechat#11]
- [x] success
- [x] error
- [x] warning
- [x] custom color
- [x] apply on storybook
- [x] multiple alerts
- [x] auto close

![image](https://user-images.githubusercontent.com/5263975/44047111-e166097c-9f03-11e8-9028-a411e0b8ab84.png)

**Comment by diegolmello** [comment]
Fixed on #92
