### ISSUE TITLE
Dismiss modal/popover on 'esc'

### ISSUE THREAD

**Issue by ggazzo** [RocketChat/Rocket.Chat.Livechat#143]

**Comment by Aditya-Kolla** [comment]
Can I work on this?

**Comment by renatobecker** [comment]
@Aditya-Kolla, yes.. feel free to work on this PR.
Thanks.

**Comment by Aditya-Kolla** [comment]
@renatobecker I'm opening a PR regarding this. Please guide me.Thank you :D
