### ISSUE TITLE
Getting error while installing dependencies using yarn and npm 

### ISSUE THREAD

**Issue by jervis446** [RocketChat/Rocket.Chat.Livechat#147]
**What is the current behavior?**

Yarn fails to install and does not provide any helpful error message for debugging. I have already done this:

rm -rf node_modules
rm -rf /Users/jarvis446/Library/Caches/Yarn
..but it has not made any difference.

**steps to reproduce**

![image](https://user-images.githubusercontent.com/22105326/52075892-6d061680-25b3-11e9-8b3f-6914578a1d07.png)

**node.js, yarn and operating system version**
Node: 6.5.0
Yarn: 1.12.3
Ubuntu 16.04.5 LTS (Xenial Xerus)

**Comment by tassoevan** [comment]
It's failing to fetch https://github.com/gwicke/web-streams-polyfill, a dependency of https://github.com/RocketChat/Rocket.Chat.js.SDK. Are you behind a proxy, firewall, or something else blocking git's access to GitHub?

**Comment by jervis446** [comment]
@tassoevan Thanks, ya I get it. My College network is under a firewall that is why.

**Comment by jervis446** [comment]
Now I'm closing the issue :)
