### ISSUE TITLE
Image that is upload to message is not shown

### ISSUE THREAD

**Issue by jervis446** [RocketChat/Rocket.Chat.Livechat#161]
**What is the current behavior?**

![imagetest](https://user-images.githubusercontent.com/22105326/52976961-90bdbf00-33f1-11e9-9e7a-df675a364b69.png)

**node.js, yarn and operating system version**
Node: 6.5.0
Yarn: 1.12.3
Browser: Chrome
Ubuntu 16.04.5 LTS (Xenial Xerus)

**Comment by renatobecker** [comment]
@jervis446, can you please check your browser console to see if something is displayed?
I'll be waiting for your feedback.

Thanks.

**Comment by jervis446** [comment]
![errorimg](https://user-images.githubusercontent.com/22105326/52990892-3f80f000-3430-11e9-83a2-d6139e95a08c.png)

it shows error: Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by jervis446** [comment]
hi ,@renatobecker can I work on this?

**Comment by renatobecker** [comment]
@jervis446 
Does this issue happen just after the file is uploaded? Is the attachment preview not showing?
It's weird behavior, would you be able to share a video recording of this process?

Thanks.

**Comment by jervis446** [comment]
For Sure
