### ISSUE TITLE
'Unread messages' and Notification badge don't update.

### ISSUE THREAD

**Issue by Aditya-Kolla** [RocketChat/Rocket.Chat.Livechat#170]
There should be some sort of a way to figure out how to remove the unread messages tag. 
**Expected behaviour**: When you open the chat or the focus is on Input box, the unread messages tag should disappear along with the notification badge.

**Comment by Aditya-Kolla** [comment]
Suggestions? 
If it's correct, can I work on this?

**Comment by renatobecker** [comment]
@Aditya-Kolla, the default behavior is to unread messages stuff when the Livechat user sends a new message.

**Comment by Aditya-Kolla** [comment]
Alright :) Closing this issue then.
