### ISSUE TITLE
how to install to an existing rocket chat server

### ISSUE THREAD

**Issue by ccfiel** [RocketChat/Rocket.Chat.Livechat#173]
Can this be install to existing rocket chat instance? or still alpha mode?

**Comment by renatobecker** [comment]
@ccfiel, currently this version is only served as an `Enterprise` feature.
But we have plans to release it as a `Community` feature very soon.

Thanks.

**Comment by voordev** [comment]
Any new updates on this since its not released? 
Some documentation would be very welcome.
thank you.
