### ISSUE TITLE
Allow users to send messages while they are in the queue

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat.Livechat#193]
It is very annoying not being able to send a message while waiting to be connected.

![image](https://user-images.githubusercontent.com/1000217/54392466-8310f780-4686-11e9-9a74-c9d99c171e70.png)

**Comment by renatobecker** [comment]
Actually, we have a setting that allows this behavior:

<img width="523" alt="Screen Shot 2019-03-17 at 13 09 21" src="https://user-images.githubusercontent.com/2067649/54494149-154b1280-48b6-11e9-8f67-d35462408d82.png">

The point is that the setting was not activated on our server, so it was an issue.
I'm fixing this issue right now.

**Comment by engelgabriel** [comment]
Ok, but what is the default option @renatobecker ?

**Comment by engelgabriel** [comment]
And the "Connecting Message" should be VERY different from the Input, right now they are very easy to be confused.

**Comment by renatobecker** [comment]
@engelgabriel, the default option is to allow users chatting even when connecting to an agent.

**Comment by engelgabriel** [comment]
Let's remove this setting, I think it is pretty much useless. As long as we clarify the message with a banner on top, explaining that the user in in a queue and an agent will reply as soon as possible, we don't need to prevent the visitor from typing.

**Comment by renatobecker** [comment]
> Let's remove this setting, I think it is pretty much useless. As long as we clarify the message with a banner on top, explaining that the user is in a queue and an agent will reply as soon as possible, we don't need to prevent the visitor from typing.

Okay.. I'm going to work on it.
