### ISSUE TITLE
livechat: internationalization api

### ISSUE THREAD

**Issue by hlehmann** [RocketChat/Rocket.Chat.Livechat#206]
### Description:

I need to have texts depending on the main page locale.
Could it be possible to have `setLocale` for livechat messages (menu, close conversation...) and `setCustomTexts` for titles and other custom texts.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: no
* Node Version: v8.11.2
* mongoDB Version: 3.6

**Comment by renatobecker** [comment]
The `setLanguage` method is available on the new Livechat client:
https://github.com/RocketChat/Rocket.Chat.Livechat/pull/214

**Comment by cewi** [comment]
Short question;
I added 
`RocketChat(function() {
    this.setLanguage('de');
});
`
after the snippet which includes the widget. But the language of the widget is still english.
My rocket.chat server is 1.2.1.

**Comment by renatobecker** [comment]
> Short question;
> I added
> `RocketChat(function() { this.setLanguage('de'); }); `
> after the snippet which includes the widget. But the language of the widget is still english.
> My rocket.chat server is 1.2.1.

Hi @cewi, I just tested the method you mentioned(setLanguage) and it's working fine.
Can you please call the method in your browser console to check what happens?

**Comment by cewi** [comment]
Sorry, was off for a while.
I embedded the code for the widget (which loads corrrectly), on my site. 
In the Browser (Firefox) Console, I get after inserting the above code:
"undefined." 
And 
"AbortError: The operation was aborted."

**Comment by cewi** [comment]
With the latest update, everything now works fine. Thankyou!
