### ISSUE TITLE
'departments.some' is not a function

### ISSUE THREAD

**Issue by Briareos12** [RocketChat/Rocket.Chat.Livechat#207]
Hello, 

I try to install Rocket.Chat.Livechat to my Rocket.Chat instance. But It seem there is some conflicts with the 'standard' livechat present on server. 
In fact when I disabled livechat on the instance and load the new livechat before to reactivate the standard livechat (to receive incoming message) it works, but only for the loaded chat (for exemple if I open a website and the chat pop up I can reactivate the livechat incoming on the Rocket.Chat instance).
I've tried to look into the log but nothing. The only error what I can see is this : 

![image](https://user-images.githubusercontent.com/16592311/55010279-38776f80-4fe4-11e9-873b-c6e7346db6a7.png)

Have any suggestion to resolve it ? 

Thanks a lot,

**Comment by Briareos12** [comment]
I've found a solution. I've modify the type to array of the variable 'departments' in the container.js.

**Comment by mtsunwin** [comment]
> I've found a solution. I've modify the type to array of the variable 'departments' in the container.js.

thanks you

**Comment by Briareos12** [comment]
I don't know.. When I'v downloaded the extension, it was like that
