### ISSUE TITLE
add Iframe to Website

### ISSUE THREAD

**Issue by mtsunwin** [RocketChat/Rocket.Chat.Livechat#217]
<script>
  (function(w, d, s, u) {
    w.RocketChat = function(c) { w.RocketChat._.push(c) };
    w.RocketChat._ = [];
    w.RocketChat.url = u;
    var h = d.getElementsByTagName(s)[0],
            j = d.createElement(s);
    j.async = true;
    j.src = 'http://localhost:8080/livechat/1.0/packages/rocketchat_livechat/assets/rocketchat-livechat.min.js?_=201702160944';
    h.parentNode.insertBefore(j, h);
  })(window, document, 'script', 'http://localhost:8080/livechat?version=1.0');
</script>

how to get file rocketchat-livechat.min.js? please help me

**Comment by knrt10** [comment]
@mtsunwin you have to build using the command `yarn build` which will create file `rocketchat-livechat.min.js` along with other files. inside `build` folder. After that you can use the relative path of file inside your script.

**Comment by tassoevan** [comment]
Please check our forum (https://forums.rocket.chat/c/community-support) and community support channel (https://open.rocket.chat/channel/support) for help.
