### ISSUE TITLE
Different possibilities livechat

### ISSUE THREAD

**Issue by deonio** [RocketChat/Rocket.Chat.Livechat#231]
Hi

Installed:
Rocket.Chat Version: 1.0.3
MongoDB Version: 4.0.9
Rocket.Chat.Livechat: Version 1.0.0

On your screenshots
![screenshot-user-images githubusercontent com-2019 05 12-17-03-21](https://user-images.githubusercontent.com/5830124/57580981-e7abcf80-74da-11e9-82a8-2eeb9d9b1ac5.png)
On the left emoji icon. When you press the plus button, four options appear

In my screenshot
![screenshot-ni-na ru-2019 05 12-17-03-41](https://user-images.githubusercontent.com/5830124/57581034-b7186580-74db-11e9-856d-04880629599f.png)
No emoji. When I click on the plus icon, I can only upload the file.

How to make the same features as you?

**Comment by knrt10** [comment]
@deonio emoji feature is work in progress. It's will soon be added. Other features including emoji are currently disabled as they are in the debugging stage and will soon be released.

**Comment by deonio** [comment]
Thank
Hope it will be soon

**Comment by renatobecker** [comment]
@deonio, for other questions like this, please use our forum: https://forums.rocket.chat/
Thanks.
