### ISSUE TITLE
How can I add additional custom field on the livechat box?

### ISSUE THREAD

**Issue by ybshin** [RocketChat/Rocket.Chat.Livechat#234]
I wanna add custom field on the livechat box before starting chatting with customer.

There is only two field name and email but I wanna add Phone number

![image](https://user-images.githubusercontent.com/10042091/57743988-8dd12280-76f1-11e9-9466-a96bbe74a2e6.png)

I already added Custom Fields same as below but I don't know how I can apply it on the livechat box.

![image](https://user-images.githubusercontent.com/10042091/57744025-ae997800-76f1-11e9-8de0-6a93a81b21f2.png)

Our current rocketchat server version
![image](https://user-images.githubusercontent.com/10042091/57745021-a5aaa580-76f5-11e9-8a08-4df01f5a695b.png)

**Comment by renatobecker** [comment]
@ybshin, It's not yet possible to add custom fields on the registration form. The custom fields are only available on the Livechat API:
https://rocket.chat/docs/developer-guides/livechat-api/#set-custom-field

**Comment by adiquet** [comment]
Is there any update on this, or any ETA?

**Comment by lithiumlab** [comment]
is there a workaround to add this field to the form as in the screenshot?

**Comment by renatobecker** [comment]
Hi Guys, I have good news on this subject:
https://github.com/RocketChat/Rocket.Chat.Livechat/pull/407

We've plans to deliver this new feature on our next release: `3.3`.

**Comment by jeyemwey** [comment]
Hi, is there a documentation on how the custom fields are displayed in the registration? I have created a custom field but it is not visible in the registration form. I have embedded the livechat via `<iframe src="https://chat.mydomain.test/livechat?mode=popout">`, and I can (probably) not modify the embed later?

**Comment by renatobecker** [comment]
> Hi, is there a documentation on how the custom fields are displayed in the registration? I have created a custom field but it is not visible in the registration form. I have embedded the livechat via `<iframe src="https://chat.mydomain.test/livechat?mode=popout">`, and I can (probably) not modify the embed later?

Hi @jeyemwey 

The ability to display custom fields in the registration form is an `Enterprise` feature, so to be able to use it you need to get an `enterprise` license.

Best Regards.

**Comment by jeyemwey** [comment]
It would have been helpful if this was advised. Thanks @renatobecker for the response.
