### ISSUE TITLE
Current Chat does not find by name

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat.Livechat#236]
Description:
I can not find in the report by name, the other fields work except the name as shown in the video below

Server Setup Information:

Version of Rocket.Chat Server: 1.0.3
Operating System: Debian 9
Deployment Method: tar
Number of Running Instances: 1
NodeJS Version: v8.15.0
MongoDB Version: v3.6.10

![bug](https://user-images.githubusercontent.com/12038013/58019140-33fa9f00-7adb-11e9-8b34-7a3b672ff4f9.gif)

**Comment by renatobecker** [comment]
Hi @josep112.
This repository is related to the Livechat widget stuff, not the Admin area.
BTW, The related issue is already fixed, as you can see here -> https://github.com/RocketChat/Rocket.Chat/issues/14395
Thanks.
