### ISSUE TITLE
Customizing Pre-Registration Message

### ISSUE THREAD

**Issue by nickian** [RocketChat/Rocket.Chat.Livechat#241]
Can we customize this message on the Pre-Registration?: 

"Please, tell us some informations to start the chat"

It at least should say "information" not "informations" and have a period at the end.

The Appearance settings page has a "Livechat_Registration_form_message" field, but I'm guessing that's for the old widget because it's not currently working for the new live chat widget.

**Comment by renatobecker** [comment]
Hi @nickian, thanks for reporting the issue on Registration Form.
Yeah, I just realized that the `Livechat_Registration_form_message` is not being rendered on the Form, I'm going to fix it now.

Thanks again.
