### ISSUE TITLE
Client does not recognize /api/v1/livechat/room.close

### ISSUE THREAD

**Issue by mhelwick54** [RocketChat/Rocket.Chat.Livechat#246]
### Description:
When closing a livechat room with `room.close` the API found [here](https://rocket.chat/docs/developer-guides/rest-api/livechat/room/), the client does not appear to recognize that the room has been closed (using the livechat API `onChatEnded`). 

### Expected Behavior:
The client should also recognize that the room has been closed/chat has been ended after a successful call to `room.close`, triggering the `onChatEnded` function. 

### Actual Behavior
When closed by either the visitor or the agent, `onChatEnded` triggers, and the conversation shows as ended on the agent window when using `room.close`. However, `onChatEnded` does not trigger for the client when using `room.close`.

**Comment by renatobecker** [comment]
Hi @mhelwick54.

How did you implement it?
I just tested the method callback and it's working fine. Look:

Assigning the callback:
![Screen Shot 2019-06-14 at 17 04 56](https://user-images.githubusercontent.com/2067649/59535229-cb7ac400-8ec6-11e9-8589-2622b72ff9cf.png)

Log on browser console:
![Screen Shot 2019-06-14 at 17 05 01](https://user-images.githubusercontent.com/2067649/59535273-e51c0b80-8ec6-11e9-9753-324af57e90da.png)

**Comment by mhelwick54** [comment]
@renatobecker Thanks for the reply, it was probably just misuse on my end. I'm no longer working on the project, so I can't do much digging to see if there was a bigger issue.
