### ISSUE TITLE
Function setGuestName in mode popout [question]

### ISSUE THREAD

**Issue by sidneiweber** [RocketChat/Rocket.Chat.Livechat#248]
is it possible to use setGuestName in popup mode?
Function works correctly in standard chat but not in popup.
I saw in the documentation the onChatMaximized event does not have change in attributes
![Captura de tela de 2019-06-21 11-07-42](https://user-images.githubusercontent.com/6644629/59928317-dc6e8c80-9414-11e9-91d0-dd54de1632c6.png)
![Captura de tela de 2019-06-21 11-07-56](https://user-images.githubusercontent.com/6644629/59928324-e0021380-9414-11e9-907e-3026889b3100.png)

**Comment by renatobecker** [comment]
@sidneiweber Have you tried the `setGuestName` on our new livechat widget?
The old version will be deprecated very soon.

**Comment by sidneiweber** [comment]
Actually in the new version works correctly. But I have a problem.
I'm using url livechat?version=1.0.0&mode=popout to embed in an application, but sometimes it does not access with the structure it should

Expected:
![Captura de tela de 2019-06-21 17-07-17](https://user-images.githubusercontent.com/6644629/59948657-2b351a00-9447-11e9-8698-568564c88bf2.png)

Result:
![Captura de tela de 2019-06-21 17-07-48](https://user-images.githubusercontent.com/6644629/59948685-47d15200-9447-11e9-9133-e726181f37bf.png)

**Comment by sidneiweber** [comment]
behavior on mobile phones seems to be quite different
