### ISSUE TITLE
Bot integration via webhook

### ISSUE THREAD

**Issue by grumpygordon** [RocketChat/Rocket.Chat.Livechat#259]
Hello. This question might be very simple, but I've failed to find an answer to it in docs. So here it is, I use rasa bot and I integrated it with rocketchat via outgoing webhook, I want to use it for the purpose of talking to users via livechat. The problem is I can't configure webhook the way that it listens only to livechats that it is part of. This might become a huge problem, as bot does some actions not related to the chat, which might cause a lot of problem if triggered accidentally. I thought that it might be possible with the script in the webhook, but for that I would need some additional information about the chat, which is not present in the json. I saw that you have some bot enviroment, I believe it might be useful in my case. If so, can someone help me with how to run bot configuration and point rasa server to rocketchat without webhook. Thanks in advance.

**Comment by renatobecker** [comment]
I think your question should be created in our forum, don't you?
But to clarify all things: The payload we send to your endpoint will contain the `agent` data, so it's pretty easy to check if it's a message related to a room that your `bot` is assigned to. Did you check the sample below?

https://rocket.chat/docs/administrator-guides/livechat/#integrations

**Comment by grumpygordon** [comment]
Actually I wanted to clarify if there is something like 'all_livechat_rooms' similar to 'all_direct_messages', but you are right, that I should've done this in forum.
