### ISSUE TITLE
How to properly update department name?

### ISSUE THREAD

**Issue by carlo-fontanos** [RocketChat/Rocket.Chat.Livechat#281]
Hi, 

I am trying to update the department name using the following code but I keep getting the response `{"success":false}` with no other information to help understand the error. 

```
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
$(document).ready(function(){
	$.ajax({
		type: 'POST',
		url: 'https://example.com/api/v1/login', 
		data: {
			'user': 'myusername',
			'password': 'mypassword'
		}, 			
		success: function(response) {
			$.ajax({
				type: 'PUT',
				headers: {
					'X-Auth-Token': response.data.authToken,
					'X-User-Id': response.data.userId
				},
				url: 'https://example.com/api/v1/livechat/department/hxLkPGPRZBfmHbJpt', 
				dataType: 'json',
				contentType: 'application/json',
				data: JSON.stringify({
					department: {name: 'test new name'}
				})
			});
		}					
	});
});
</script>
```

I use this documentation page as reference: https://rocket.chat/docs/developer-guides/rest-api/livechat/department/index.html#update-a-department

**Comment by renatobecker** [comment]
Hi @carlo-fontanos.
Does the logged user have the `view-livechat-manager` permission?
https://github.com/RocketChat/Rocket.Chat/blob/master/app/livechat/imports/server/rest/departments.js#L65

I guess you aren't passing the `agents` parameter, right?
https://github.com/RocketChat/Rocket.Chat/blob/master/app/livechat/imports/server/rest/departments.js#L76

**Comment by carlo-fontanos** [comment]
Hi @renatobecker,

The logged in user has admin role with `view-livechat-manager` permission. Please refer to attached screenshot: 

![image](https://user-images.githubusercontent.com/12164593/64311152-923d8600-cfd5-11e9-9943-6f32d9585617.png)

I am not passing the `agents` array because I only need to update the department name. Is it required to pass the `agents` array?

**Comment by carlo-fontanos** [comment]
I tried including the `agents` array but still getting the same response `{"success":false}`

Here's the code I tried: 

```
$.ajax({
	type: 'POST',
	url: 'https://example.com/api/v1/login', 
	data: {
		'user': 'myusername',
		'password': 'mypassword'
	}, 			
	success: function(response) {
		// Get user
		$.ajax({
			type: 'PUT',
			headers: {
				'X-Auth-Token': response.data.authToken,
				'X-User-Id': response.data.userId
			},
			url: 'https://example.com/api/v1/livechat/department/hxLkPGPRZBfmHbJpt', 
			dataType: 'json',
			contentType: 'application/json',
			data: JSON.stringify({
				"department": {
					"enabled": true,
					"showOnRegistration": true,
					"name": "new from api - live"
				},
				"agents": [{
					"agentId": "pDHJQnitMYyot6QAN",
					"username": "agent.un1",
					"count": 0,
					"order": 0
				}]
			})
		});
	}					
});
```

**Comment by renatobecker** [comment]
@carlo-fontanos 
The 'agents' is a mandatory field, as you can see here:
https://github.com/RocketChat/Rocket.Chat/blob/master/app/livechat/imports/server/rest/departments.js#L76

Unfortunately, the PUT method is not returning the correct error when something goes wrong, as you can see here:
https://github.com/RocketChat/Rocket.Chat/blob/master/app/livechat/imports/server/rest/departments.js#L88
To display an eventual error we just need to return the -> `return API.v1.failure(e)`.

But, the point is that there are some fields still missing on your request, please take a look at here:
https://github.com/RocketChat/Rocket.Chat/blob/master/app/livechat/server/lib/Livechat.js#L769

I agree that we can make the `agents` fields optional, so I suggest you open a new issue requesting this change, what do you think?

Thanks.

**Comment by carlo-fontanos** [comment]
Hi @renatobecker,

Thanks for helping out. You are right, the missing fields on my code was on the `department` array. I had to provide all the fields to get it working: 

data: JSON.stringify({
	"department": {
		"enabled": true,
		"showOnRegistration": true,
		"name": "new from api - live",
		"description": "test desc",
		"email": "test@gmail.com",
		"showOnOfflineForm": true
	},
	"agents": [{
		"agentId": "pDHJQnitMYyot6QAN",
		"username": "testusername",
		"count": 0,
		"order": 0
	}]
})

I think you should update the Example Payload on the **Update Department** section to include all the required department fields: https://rocket.chat/docs/developer-guides/rest-api/livechat/department/index.html#update-a-department

I've opened a new issue requesting to make the `agents` array optional: https://github.com/RocketChat/Rocket.Chat.Livechat/issues/286
