### ISSUE TITLE
Using setGuestEmail and setGuestName causes grayed out "Start chat" button

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Livechat#282]
When using `setGuestEmail` and `setGuestName` the start button is grayed out. 

![image](https://user-images.githubusercontent.com/6295044/64410493-2866c000-d059-11e9-91ca-76519a6fb774.png)

Example Code:
```
RocketChat(function () {
    this.setTheme({
        color: '#27AAE1', // widget title background color
        fontColor: '#FFFFFF' // widget title font color
    });
    this.setDepartment('Department Name');
    this.setGuestEmail(Meteor.user().emails[0].address);
    this.setGuestName(Meteor.user().profile.name);
});
```

**Expected behavior**
If you provide all of the guest information required, it should automatically start the chat and skip the information step.

**Comment by renatobecker** [comment]
If you want to skip the registration form then you need to call the `registerGuest` method.
https://rocket.chat/docs/developer-guides/livechat-api/#register-visitor
