### ISSUE TITLE
Installation of new version of Rocket.Chat Livechat not working

### ISSUE THREAD

**Issue by carlo-fontanos** [RocketChat/Rocket.Chat.Livechat#288]
Hi, 

I copied the live chat (new version) code provided in the Rocketchat Livechat installation page and placed it in a test.html file, but when I try to access the file, nothing shows up, and on my Firefox console I get 3 errors: 

![image](https://user-images.githubusercontent.com/12164593/64836858-61d19980-d61e-11e9-8b90-db50dcdbbb9e.png)

Here's the Rocketchat Livechat installation page: 

![image](https://user-images.githubusercontent.com/12164593/64836924-a826f880-d61e-11e9-8e58-4a04d29feb71.png)

Here's the livechat code (new version) in case you need to test: 
```
<!-- Start of Rocket.Chat Livechat Script -->
<script type="text/javascript">
(function(w, d, s, u) {
	w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
	var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
	j.async = true; j.src = 'https://cyberauctionschat.com/livechat/1.0.0/rocketchat-livechat.min.js?_=201903270000';
	h.parentNode.insertBefore(j, h);
})(window, document, 'script', 'https://cyberauctionschat.com/livechat?version=1.0.0');
</script>
<!-- End of Rocket.Chat Livechat Script -->
```

**Comment by renatobecker** [comment]
Remove the `1.0.0` from the path url:
`https://cyberauctionschat.com/livechat/rocketchat-livechat.min.js?_=201903270000';
	h.parentNode.insertBefore(j, h)`

**Comment by carlo-fontanos** [comment]
Ok that fixed the problem, but consider updating the Rocketchat Livechat installation page too so that other developers in the future will not encounter the same problem.

**Comment by Sx3** [comment]
Removing the 1.0.0 worked for me too.
Thanks.
