### ISSUE TITLE
Latest version of Livechat Widget does not pop in the web page

### ISSUE THREAD

**Issue by PedroPretto** [RocketChat/Rocket.Chat.Livechat#290]
### Description:

We have an infrastructure based on multiple rocketchats running in containers installed outside the root(/), after installed update 1.3.0v, the new livechat widget does not pop in the sites. E.g:
domain.com.br/rocketchat1
domain.com.br/rocketchat2

### Steps to reproduce:

1. Set up the rocketchat config on docker
2. Set up the latest version of rocketchat Livechat in your website
3. Go to the web page with embedded livechat widget

### Expected behavior:

The Livechat widget to pop up in the inferior right corner of the web page.

### Actual behavior:

The widget does not show anywhere in the site.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.0
- Operating System: Debian 9 (Stretch)
- Deployment Method: Docker
- Number of Running Instances: 3
- MongoDB Version: 4.0

![image](https://user-images.githubusercontent.com/38132954/63458163-a2c3fd00-c428-11e9-9545-5cec3c93f44b.png)

This is what my console shows when the configurations are applied.

**Comment by maciej87pl** [comment]
I upgrade to 2.0 and do some test. Maybe this will help: when I use this code for widget:
`<script type="text/javascript">
(function(w, d, s, u) {
	w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
	var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
	j.async = true; j.src = '**https**://domain/livechat/rocketchat-livechat.min.js?_=201903270000';
	h.parentNode.insertBefore(j, h);
})(window, document, 'script', '**https**://domain/livechat');
</script>`
Livechat is showing in firefox and chrome in incognito mode
When I am using this code:
`<script type="text/javascript">
(function(w, d, s, u) {
	w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
	var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
	j.async = true; j.src = '**http**://domain:**3000**/livechat/rocketchat-livechat.min.js?_=201903270000';
	h.parentNode.insertBefore(j, h);
})(window, document, 'script', '**http**://domain**:3000**/livechat');
</script>`
It works in firefox and Chrome in both mode (normal and incognito)
