### ISSUE TITLE
Request: Make Widget `open`able through the WidgetAPI

### ISSUE THREAD

**Issue by Blackskyliner** [RocketChat/Rocket.Chat.Livechat#293]
Currently, as far as documentation of this component goes, it seems to be impossible to open the widget through a scripted page event.

At some sites I maintain we load the livechat on-demand per button click of the user. Then the user needs to click again on the widget itself to open the chat.

I patched this behavior in with the old chat for myself by just setting `data-state` to `opened` and set a width and height of the widget container, but this seems to not work anymore with this new version because the state is held reactive inside the widget.

Therefore I would like to request to add the `openWidget` (and maybe the `closeWidget`) method to the public API of the widget.

**Comment by renatobecker** [comment]
Hi @Blackskyliner 
You're probably looking for these methods -> https://github.com/RocketChat/Rocket.Chat.Livechat/pull/280

They'll be available on our next release.
Thanks.

**Comment by Blackskyliner** [comment]
Yes indeed, I just did not find it because it's called minimize and maximize instead of open and close. Thanks!
