### ISSUE TITLE
trigger RC 2.x

### ISSUE THREAD

**Issue by PointPubMedia** [RocketChat/Rocket.Chat.Livechat#299]
Hi,

Since we migrate to RC 2.x , it seems that the trigger function is not working anymore on Google chrome...

On firefox it's working and on IE the badge is not loading at all.

**Comment by renatobecker** [comment]
@PointPubMedia thanks for reporting.
We'll take a look into this issue.

**Comment by ubergeekzone** [comment]
To fix the triggers this is related to a `RangeError: Invalid time value` 

in the file `lib/triggers.js` go to line 114 and change it from `ts: new Date()` to `ts: new Date().toISOString()`

this will allow triggers to work again.

**Comment by renatobecker** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Livechat/pull/320.
