### ISSUE TITLE
Run LiveChat from HTTPS deployment -> avoid "Mixed Content: was loaded over HTTPS, but requested an insecure resource"

### ISSUE THREAD

**Issue by HudsonProdigy** [RocketChat/Rocket.Chat.Livechat#317]
Hello,
I am having issues running Live chat from https deployment of rocketchat. It seems the main issue is in function e.get() from Rocket.Chat.js.SDK.c...c4.js. It seems that the host name it gets is what is configured in /lib/systemd/system/rocketchat.service which is the http binding. Is there a way to change host to use the internet available(behind reverse proxy) hostname instead?

Any help would be much appreciated.  IM sure im missing something because i have not found anyone else with this problem yet in issues or other posts.

Thanks

**Comment by HudsonProdigy** [comment]
Hello for anyone who comes across this it turns out hostname is stored in mongo db on first run and does not change value when you edit /lib/systemd/system/rocketchat.service. so to change url post install you must modify mongo db: open mongo shell -> use rocketchat -> db.rocketchat_settings.update({"_id" : "Site_Url"},{$set:{value:"NEW_URL/"}})

**Comment by renatobecker** [comment]
> Hello for anyone who comes across this it turns out hostname is stored in mongo db on first run and does not change value when you edit /lib/systemd/system/rocketchat.service. so to change url post install you must modify mongo db: open mongo shell -> use rocketchat -> db.rocketchat_settings.update({"_id" : "Site_Url"},{$set:{value:"NEW_URL/"}})

Hello!

You just need to change the `Site_Url` on the Rocket.Chat admin area. Have you tried it?

**Comment by HudsonProdigy** [comment]
after reboot of machine. my instance has failed. going to undo what i did and try your method. will post back result

**Comment by HudsonProdigy** [comment]
Hey @renatobecker  i redeployed manual install on ubuntu from scratch following install instructions from rocketchat website. i then installed nginx from guide on website aswell and configured. install went well, but once i changed site_url as you recommended i could no longer access the site. and am thrown into to many redirects error.

**Comment by renatobecker** [comment]
> Hey @renatobecker i redeployed manual install on ubuntu from scratch following install instructions from rocketchat website. i then installed nginx from guide on website aswell and configured. install went well, but once i changed site_url as you recommended i could no longer access the site. and am thrown into to many redirects error.

Can you please share the error you getting?

**Comment by HudsonProdigy** [comment]
can you clarify what changing site_url variable does? i want the application to bind to port 3000. i run reversproxy with nginx on 443 to redirect to port 3000 binding. does changing site_url variable in application change the port application binds to?

**Comment by renatobecker** [comment]
The `SITE_URL` is the address where the Livechat widget will call the REST API endpoints, as well as connect the WSS.

**Comment by HudsonProdigy** [comment]
okay great thats what i am looking for. Seems like when i changed it that it updated site binding. is this expected behaviour?

**Comment by renatobecker** [comment]
> okay great thats what i am looking for. Seems like when i changed it that it updated site binding. is this expected behaviour?

When you change the `SITE_URL` in the admin area, we need to change the Javascript snippet on the website you're running the widget.

**Comment by HudsonProdigy** [comment]
okay yes. i get this. my issue is once i changed the SITE_URL i could no longer access rocketchat because it changed binding from 3000 to the https://chat.domain.com i entered in admin center. Going to confirm order of operations. install rocket chat on port 3000(http://chat.domain.com:3000) -> reverse proxy on port 443 to port 3000. i can now access from internet over https(https://chat.domain.com). -> modify site_url in admin center to -> https://chat.domain.com...?

**Comment by renatobecker** [comment]
If you have Rocket.Chat running in a specific IP on port = 3000, then you'll be able to access Rocket.Chat from both intranet(IP:PORT) and internet(SITE_URL). So, for sure you need to set the SITE_URL setting in order to provide the URL where the Livechat widget will call the REST API.

**Comment by HudsonProdigy** [comment]
Okay thanks for help. a lot further along now. having issue that start chat button is loading forever. no errors in console that seem related. nothing in service status as well.

**Comment by HudsonProdigy** [comment]
it looked like websocket issue. had to do with iis reverse proxy i had up. removed it and went strait to rocket chat server. all sorted. thanks very much for your help @renatobecker !
