### ISSUE TITLE
Additional fields on the livechat box

### ISSUE THREAD

**Issue by unixfox** [RocketChat/Rocket.Chat.Livechat#319]
Your Rocket.Chat version: 0.40.0
## Explanation of the idea

It could be great to introduce a ability to add additional fields on the livechat box.
Additional fields could be synchronized with `custom fields`.
And a possibility to require some fields.
## Idea in image

![capture du 2016-09-21 14-04-51](https://cloud.githubusercontent.com/assets/4016501/18710235/683db95c-8004-11e6-9942-ba023da51993.png)

**Comment by adiquet** [comment]
> Hi @fabiothoma!
> 
> We started working on our new Livechat client, so we'll probably implement this feature there.
> You can follow the development status here:
> https://github.com/RocketChat/Rocket.Chat.Livechat
> 
> Thanks.

How would you install this? Just replace the files located in /app/livechat ?

**Comment by unixfox** [comment]
@renatobecker is the feature implemented that you are closing this issue?

**Comment by renatobecker** [comment]
> @renatobecker is the feature implemented that you are closing this issue?

Yeah! As you can see we (finally) implemented support for custom fields on our livechat widget solution. 😊
