### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by pstast** [RocketChat/Rocket.Chat.Livechat#333]
What is the official way to provide translation of Livechat? I did not found Livechat texts on Lingohub. I see **src/i18n** folder, but I think these files are auto-generated? How can I help with translation to one language?

**Comment by renatobecker** [comment]
As described on the `README` page, you just need to run:
```
# before commit run
yarn i18n
```

After that, you will find the related `i18n` file where you can change the translations.
