### ISSUE TITLE
How are we to remove open Livechat rooms

### ISSUE THREAD

**Issue by GetGeeks** [RocketChat/Rocket.Chat.Livechat#337]
How can we close and delete open livechats?
Previous issues left many open which I can't see how to close or delete.
Am I missing something obvious?
Is there documentation on how to flush out all livechats manually somewhere?

**Comment by renatobecker** [comment]
> How can we close and delete open livechats?
> Previous issues left many open which I can't see how to close or delete.
> Am I missing something obvious?
> Is there documentation on how to flush out all livechats manually somewhere?

To achieve this you need to have access to the Livechat admin area.
It's not related to the `Livechat Widget` repo.

**Comment by GetGeeks** [comment]
Sure from the admin area?

**Comment by GetGeeks** [comment]
Or from the db directly?

**Comment by GetGeeks** [comment]
Rooms created for each livechat have been getting left behind. The conditions might have been fixed already however these open livechat rooms remain. I have been able to delete the closed ones from the livechat admin areas but the open ones how are they to be removed?

**Comment by GetGeeks** [comment]
In case anyone else has this problem the solution for me was 
Goto admin>livechat>How to Handle Open Sessions When Agent Goes Offline 
change to "Close" then turn off livechat after a moment
old stuck open rooms close and can be deleted
from livechat>current chats (/livechat-manager/current)
