### ISSUE TITLE
Firefox error: SyntaxError: expected expression, got '<'             rocketchat-livechat.min.js:1

### ISSUE THREAD

**Issue by nodje** [RocketChat/Rocket.Chat.Livechat#338]
Rocket livechat doesn't work anymore.
I've got this error showing up in the Console.

Is there anything that requires a change on my end?

**Comment by renatobecker** [comment]
> Rocket livechat doesn't work anymore.
> I've got this error showing up in the Console.
> 
> Is there anything that requires a change on my end?

Does the Livechat work in other browsers?

**Comment by nodje** [comment]
Annoyingly, Chrome returns another error 
`main.js:79 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://ourserver.com/packages/rocketchat_livechat/assets/rocketchat-livechat.min.js with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

which also prevents the Livechat frame from showing up.

**Comment by renatobecker** [comment]
> Annoyingly, Chrome returns another error
> `main.js:79 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://ourserver.com/packages/rocketchat_livechat/assets/rocketchat-livechat.min.js with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`
> 
> which also prevents the Livechat frame from showing up.

For sure, you need to update the `Livechat snippet script installation`.
The script installation has been changed, so you'll need to update it.

**Comment by nodje** [comment]
Would you be kind enough to point me to the relevant documentation?

I've installed Rocket server as a snap package on Ubuntu, and it sure is super convenient to get auto-updates.
The inconvenience is that I never have to read the release notes anymore!

Is there a Git page to subscribe to or anything like that to stay aware of changes?

**Comment by renatobecker** [comment]
Sure, you need to go to the Livechat installation page and then copy the code you'll find there.
For instance:

https://your-server-url/livechat-manager/installation

**Comment by reetp** [comment]
> The inconvenience is that I never have to read the release notes anymore!

https://github.com/RocketChat/Rocket.Chat/releases/
 
> Is there a Git page to subscribe to or anything like that to stay aware of changes?

Go to the repo you want to watch and click "Watch" .....
