### ISSUE TITLE
[Regression] LiveChat Custom Field Endpoint does not exist

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.Livechat#350]
### Description:
LiveChat Custom Field Endpoint does not exist

### Steps to reproduce:

1. Put livechat widget on page with some custom fields
2. Load page
3. Check console logs

### Expected behavior:

No errors, successful post to livechat custom.field API.

### Actual behavior:

```
{"status":"error","message":"API endpoint does not exist"}
```
![Clipboard - January 6, 2020 6_00a PM](https://user-images.githubusercontent.com/6295044/71984800-8d911480-31f7-11ea-88bd-57f16313c057.png)
![Clipboard - January 6, 2020 6_00 PM](https://user-images.githubusercontent.com/6295044/71984803-8d911480-31f7-11ea-9820-4dd617d75cea.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.0 (097c7c04f7a07f8498d5482b7730ca81a14bd7bd)

### Client Setup Information

- Desktop App or Browser Version: Version 79.0.3945.117 (Official Build) (64-bit)
- Operating System: Windows 10

**Comment by renatobecker** [comment]
hi @wreiske,

I just tested the related endpoint and it worked fine.
I need a bit more information about your case to look into this issue, but there is a problem on the test you performed, I mean, that endpoint only accepts a **POST** request and you attempted a **GET** request on your browser, because of that you got the `{"status":"error","message":"API endpoint does not exist"}` error.

So, my questions are: 
- What is the custom field you're trying to update?
- Does the custom field exist in the Livechat configuration area?

I'll be waiting for your reply.

**Comment by renatobecker** [comment]
Additional information:

I just simulated an example where I'm trying to update a custom field that doesn't exist, look:

![Screen Shot 2020-01-08 at 11 58 10](https://user-images.githubusercontent.com/59577424/71988216-3ea2a980-320e-11ea-89b1-e2f1e7809aef.png)


As you can see, I get an error pretty similar you got on your environment.

**Comment by wreiske** [comment]
```
(function (w, d, s, u) { w.RocketChat = function (c) { w.RocketChat._.push(c) };
  w.RocketChat._ = [];
  w.RocketChat.url = u; var h = d.getElementsByTagName(s)[0],
    j = d.createElement(s);
  j.async = true;
  j.src = 'https://server/livechat/rocketchat-livechat.min.js';
  h.parentNode.insertBefore(j, h); })(window, document, 'script', 'https://server/livechat');
RocketChat(function () { 
this.setDepartment('MIE Help Desk');
  this.setCustomField('user_id', '1');
  this.setCustomField('username', 'test');
  this.setCustomField('system_handle', 'something');
  this.setCustomField('user_ip', '192.168.242.22');
  this.setCustomField('current_url', window.location.href);
  this.setGuestName('Guest name'); 
});
```

I'm not doing a POST or a GET, I'm using the Livechat API to set the custom field.

**Comment by wreiske** [comment]
Closing this.

For those of you coming here from google, the solution was to set the custom field "scope" to "visitor" instead of "room".

Also, you may want to wrap these in an onChatStarted event:
https://rocket.chat/docs/developer-guides/livechat-api/#onchatstarted

**Comment by renatobecker** [comment]
As @wreiske described, a`custom field` with the scope = room needs that the `room` exists to apply the `setCustomField` method properly.

So, to achieve this, it's necessary to use the `onChatStarted ` callback to fire the `setCustomField` method.
