### ISSUE TITLE
Closed livechat conversation stuck in left sidebar

### ISSUE THREAD

**Issue by jdaviescoates** [RocketChat/Rocket.Chat.Livechat#368]
It would appear that sometimes closed chat remain in the left sidebar as if it were still open (even thought it says in the main window that the chat has closed:

![close_chat_still_in_left_sidebar](https://user-images.githubusercontent.com/2113743/74529892-b2785600-4f20-11ea-874b-3ed2c407c772.png)

I guess I could Hide the room, but why is it still there at all if the chat is closed? (as indicated at the bottom of the screen where it says "This conversation is already closed").

None of the other closed conversations are stuck there, so not sure why this one is (but perhaps it was never actually closed by the guest but eventually timed out or something?)

**Comment by renatobecker** [comment]
@jdaviescoates what is your server version?
Anyway, you can hide de room easily:

![Screen Shot 2020-02-14 at 09 56 59](https://user-images.githubusercontent.com/59577424/74533448-602f3900-4f10-11ea-8f16-fecda36f4661.png)

**Comment by jdaviescoates** [comment]
I'm running Rocket.Chat 2.4.9 on a [Cloudron](https://cloudron.io/) server hosted on a Hetzner VPS running Ubuntu 18.04 if that helps? (sorry, wasn't exactly sure what you meant by server version?)

I realise I can hide the room, but clearly something is awry - why is this livechat conversation still showing up there and none of the others that are closed?

Out of interest, technically, are the other ones just (automatically) hidden too when they are closed? or do they have some other status which remove them? Thanks!

**Comment by renatobecker** [comment]
Something went wrong after ending the conversation, probably.
But that will no longer happen after the release `3.0`. We are now removing the "subscription" from the room when an agent closes a conversation, so for sure, this case will not happen again.

Thanks.

**Comment by jdaviescoates** [comment]
OK thanks, I'll close this then and only re-open if it occurs again :)
