### ISSUE TITLE
Wrong avatar displayed (apart from on left sidebar in web app)

### ISSUE THREAD

**Issue by jdaviescoates** [RocketChat/Rocket.Chat.Livechat#369]
I guess this may be related to #237 (and potentially to #368 too) but it's a different issue.

I was just testing my livechat set-up using name 'Testing livechat' but the avatar showing in the chat window on the website was a G instead of a T:

![Wrong_avatar](https://user-images.githubusercontent.com/2113743/74532112-426cce80-4f26-11ea-8b64-9cd5e1d8f742.png)

Confusingly when looking at the web client as the agent it was still a G in the main window, but correctly shows as a T in the sidebar:

![wrong_avatar_2](https://user-images.githubusercontent.com/2113743/74532307-cfb02300-4f26-11ea-88fe-fd1a3e75dc5c.png)

Perhaps something to do with the avatar of the closed but still stuck in the left sidebar livechat conversation (as per #368 ) being a chat with a person with a G avatar?

**Comment by jdaviescoates** [comment]
Just to add, I've now manually hidden the livechat conversation room which was stuck in the left sidebar in spite of being closed (as per #368), but this hasn't had an impact on this issue.  Every single new guest now has a G avatar in the chat room (but the correct letter avatar in the sidebar on the left).

**Comment by renatobecker** [comment]
This is happening because of the avatar is being generated from the `username` instead of `name` of the Guest.

**Comment by jdaviescoates** [comment]
Aha, that makes sense, and all of the livechat `username`s are `guest-x` which of course _does_ start with a G.

I'm _think_  that in the past this wasn't an issue though? Were avatars previously generated from `name`? If not, I guess I must just be mis-remembering and just never noticed it previously!

**Comment by ashwaniYDV** [comment]
hi @renatobecker I think it gives a bad user experience if their avatar is `G` as they don't know about the avatar generation criteria of `username=guest-xx`
I think we should use the provided name for avatar in case of guest and normal avatar for livechat agent.

**Comment by renatobecker** [comment]
> hi @renatobecker I think it gives a bad user experience if their avatar is `G` as they don't know about the avatar generation criteria of `username=guest-xx`
> I think we should use the provided name for avatar in case of guest and normal avatar for livechat agent.

Yeah, I totally agree..  but we need to ensure that the guest/visitor has a  valid`name` prop, otherwise, we should use the `username` as we have been doing.

**Comment by renatobecker** [comment]
Sorry @ashwaniYDV, I just noticed you submitted a PR fixing this issue..
But remember the same issue is happening on the web client, I mean, o the Agent-side.

**Comment by ashwaniYDV** [comment]
@renatobecker I'll try to fix it there too

**Comment by renatobecker** [comment]
> @renatobecker I'll try to fix it there too

Thank you very much.
