### ISSUE TITLE
There are some problems with "this.minimizeWidget()"

### ISSUE THREAD

**Issue by goldcome** [RocketChat/Rocket.Chat.Livechat#374]
When i run:
```
RocketChat(function() {
    this.minimizeWidget();
});
```

result:

![未标题-1](https://user-images.githubusercontent.com/2740261/75155995-1d5d3480-574c-11ea-9297-5a004ab20dc2.jpg)

The ui is gone, but still but still placeholder，i expect this result：

```
<div class="rocketchat-widget" style="position: fixed; width: 86px; height: 86px; max-height: 100vh; bottom: 0px; right: 0px; z-index: 12345; left: auto;" data-state="closed"><div class="rocketchat-container" style="width: 100%; height: 100%;">...</div>
```

**Comment by goldcome** [comment]
this miss closeWidget function, add it to this file https://github.com/RocketChat/Rocket.Chat.Livechat/blob/d343a20a83ab7cf176564d68d2bf8dbca5989d97/src/widget.js#L202

```
closeWidget() {
    closeWidget()
}
```

**Comment by goldcome** [comment]
already fixed，close it

**Comment by redrage54** [comment]
still there in RocketChat version 3.16.3
