### ISSUE TITLE
Feature request: Live chat holiday hours

### ISSUE THREAD

**Issue by mirhunter** [RocketChat/Rocket.Chat.Livechat#375]
We would like a feature to schedule holiday hours that would over ride regular office hours.
this word be great for holidays and company events that all employees attend.
for example our company has about 300+ employees that will be attending a "town hall"  (company wide meeting) during which our call center goes it to holiday mode for about 2 or 3 hours. We would like Live chat to be able do the same.

**Comment by renatobecker** [comment]
Hi @mirhunter thanks for your suggestion.
We have a specific [feature request repo](https://github.com/RocketChat/feature-requests/issues), so I suggest you create a new issue there.

Thanks.

**Comment by mirhunter** [comment]
Thanks, I have copied this request to that location.

https://github.com/RocketChat/feature-requests/issues/303#issue-572986591
