### ISSUE TITLE
[Question] How Rocket.Chat.Livechat will communicate with Rocket.Chat?

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.Livechat#38]
As in title, my question is how does Livechat will exchange data between frontend and RocketChat? Rest/Realtime API?

**Comment by sampaiodiego** [comment]
both REST and realtime. =)

realtime API will be used mainly for messages and notification events on top of MQTT (not yet implemented in Rocket.Chat) and everything else will be via REST.

**Comment by piotrkochan** [comment]
Ok then, I follow MQTT related tickets in Rocket.Chat but I don't really see any. Does it means that it is not planned in the nearest future to code MQTT protocol in RC?

**Comment by sampaiodiego** [comment]
it is planned for the near future but there is no issue/ticket because it was raised internally and bot by the community.

we'll make it "public" (since I've just said that, it's already public 😝 ) when the idea of implementation is more mature.

**Comment by piotrkochan** [comment]
@ggazzo could You update link? it is broken

**Comment by ggazzo** [comment]
sorry @piotrkochan https://github.com/RocketChat/Rocket.Chat.js.SDK/tree/multiple-clients
