### ISSUE TITLE
How to integrate  Rocket.Chat.Livechat with (Rocket.Chat.Livechat)

### ISSUE THREAD

**Issue by jimmylogic** [RocketChat/Rocket.Chat.Livechat#39]
I am looking to integrate Rocket.Chat.Livechat with (https://github.com/RocketChat/Rocket.Chat). but unable to get a way. How to do

**Comment by piotrkochan** [comment]
This project is under development and not ready to use. You can use build-in RocketChat Livechat functionality for now https://rocket.chat/docs/administrator-guides/livechat/

**Comment by sampaiodiego** [comment]
@piotrkochan is right.. this project is at component level development.. so, not ready to integrate with anything else.

**Comment by rafaellaurindo** [comment]
Hello, is it still possible to integrate this new version of Livechat with Rocket.chat?

**Comment by renatobecker** [comment]
Yeah, the new livechat is ready and will be served as a community feature.
If you're running the lasted `develop` branch, go to `/livechat-manager/installation` page and get the Javascript Snippet to install the new widget.

**Comment by rafaellaurindo** [comment]
I want to know how I can integrate a modified version of livechat with rocketchat. It's possible?

**Comment by renatobecker** [comment]
> @renatobecker I want to know how I can integrate a modified version of livechat with rocketchat. It's possible?

What kind of modifications?

**Comment by tobiasaires** [comment]
Hi, @renatobecker i work with @rafaellaurindo. And we just want to show some default message, after the user submit the form.
