### ISSUE TITLE
Send message from user after livechat window opening

### ISSUE THREAD

**Issue by tuor4eg** [RocketChat/Rocket.Chat.Livechat#402]
Hi!
I want user to select some options on the site and then click some button like "send to chat". 
And after that chat widget window should opens and automatically sends selected data as message. 
Is there any way to make like this?

**Comment by renatobecker** [comment]
@tuor4eg you can rely on the [Change widget visibility](https://rocket.chat/docs/developer-guides/livechat-api/#change-widget-visibility) and [Change widget window state][https://rocket.chat/docs/developer-guides/livechat-api/#change-widget-window-state] methods to deal with the widget appearance, but only the `visitor` is able to send messages from the widget.

But if you really need to send messages as a `visitor`, you can use the [REST API](https://rocket.chat/docs/developer-guides/rest-api/livechat/message/index.html) methods instead.

**Comment by tuor4eg** [comment]
@renatobecker thank you for answer. I tried to use REST API, but it needs authorization at any request. How can I send message as anonymous guest at the web site (like in widget) through API?

**Comment by renatobecker** [comment]
> @renatobecker thank you for answer. I tried to use REST API, but it needs authorization at any request. How can I send message as anonymous guest at the web site (like in widget) through API?

You can't send a message as anonymous, what you can do is to use the Livechat Triggers to interact with the visitors.

**Comment by MartinSchoeler** [comment]
Closing this due lack of activity on the issue, if you have further questions about the Livechat Triggers after reading our [documentation](https://docs.rocket.chat/guides/omnichannel/livechat-triggers-managers-guide) on in, feel free to create a new issue. Thanks!
