### ISSUE TITLE
[Question] Does messages in Livechat Support have support for emojis? 

### ISSUE THREAD

**Issue by murtaza98** [RocketChat/Rocket.Chat.Livechat#409]
Hello,
While working with Livechat feature, I noticed that the LiveAgent who has access to Rocket.Chat server chat interface can send an emojis to a Livechat Visitor.  However, the Livechat Visitor who is using the LiveChat Chat Interface is not able to properly render the emojis. Instead, it was showing only the placeholder title of emojis instead of actual emojis.
Have a look at SS

This is interface of LiveAgent
![image](https://user-images.githubusercontent.com/34130764/81500325-28f1dd80-92ef-11ea-960d-c83659361088.png)

And this is the interface of LiveChat Visitor
![image](https://user-images.githubusercontent.com/34130764/81500349-55a5f500-92ef-11ea-8d22-a84739ed40b7.png)

As u can see, Instead of showing the emoji icon :smile: it is displaying this ```:smile:```

I think that this problem is bcs the Livechat message component doesn't support emojis. Am I correct? 
Also, I am planning to work on adding emoji support to Livechat, so if there is any resource or suggestions u would like to share, I would appreciate it :raised_hands:

Thanks :+1:

**Comment by renatobecker** [comment]
Hi @murtaza98 Yeah, you're right, the Livechat widget doesn't support emoji rendering yet, but it would be amazing if you're willing to work on implementing this great feature!

And yes, there is a PR(WIP - https://github.com/RocketChat/Rocket.Chat.Livechat/pull/226) not completed that aims to implement emoji render, but it has not been finished, unfortunately. 

So, if you're willing to implement it, I'm available to help you with any question you may need, so just let me know.

Thanks in advance.

**Comment by murtaza98** [comment]
Hi @renatobecker 
Thanks for the PR link. It was really helpful. I think the [emoji-toolkit](https://github.com/joypixels/emoji-toolkit) module (formally emojiOne) will easily render the emojis from the title (```:smile:```) to its corresponding icon(:smile:). It can be used on the Message Component. I will try this out next.

As for the emoji-picker, I found this module named [emoji-mart](https://github.com/missive/emoji-mart), which I managed to integrate with our LiveChat Widget. Have a look at it.
![emoji_demo](https://user-images.githubusercontent.com/34130764/81507993-d16b6600-931e-11ea-945a-bbcda7f1127c.gif)

Next, the biggest challenge I think will be making this emoji-picker responsive. I will try to implement it first, and if there is some difficulty, I will reach out to you :sweat_smile: 

Thanks :smiley:

**Comment by renatobecker** [comment]
> Hi @renatobecker
> Thanks for the PR link. It was really helpful. I think the [emoji-toolkit](https://github.com/joypixels/emoji-toolkit) module (formally emojiOne) will easily render the emojis from the title (`:smile:`) to its corresponding icon(😄). It can be used on the Message Component. I will try this out next.
> 
> As for the emoji-picker, I found this module named [emoji-mart](https://github.com/missive/emoji-mart), which I managed to integrate with our LiveChat Widget. Have a look at it.
> ![emoji_demo](https://user-images.githubusercontent.com/34130764/81507993-d16b6600-931e-11ea-945a-bbcda7f1127c.gif)
> 
> Next, the biggest challenge I think will be making this emoji-picker responsive. I will try to implement it first, and if there is some difficulty, I will reach out to you 😅
> 
> Thanks 😃

Hey, @murtaza98 awesome!
This is a long-waited feature that will provide a very nice experience for the final user.
As you described, the emoji rendering is not too tricky, the emoji-picker rendering may require a bit more time to implement, so I strongly encourage you to work on this important feature :slight_smile:.
