### ISSUE TITLE
Omnichannel visitors no longer able to switch departments in v3.3.0

### ISSUE THREAD

**Issue by GarthKiepper** [RocketChat/Rocket.Chat.Livechat#428]
### Description:

Livechat visitors are unable to change departments because the "Start chat" button is disabled and grayed out. I see the button HTML is set to "disabled". **This was working in RocketChat v3.0.8 and broke after upgrading to v3.3.0**

### Steps to reproduce:

1. Go to Administration, then Omnichannel.
2. Click on the Livechat heading.
3. Scroll down to enable the setting "Allow Visitor to Switch Departments"
4. Be a livechat/omnichannel visitor and start a new chat message.
5. While still a chat guest, click "Options" in the lower left corner.
6. Click "Change Department"
7. Select a department from the drop-down menu.
8. Attempt to click "Chat now" button and observe it cannot be clicked.

### Expected behavior:

"Chat now" button should be clickable. The HTML for the button should not be set to disabled.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: ubuntu 18.04.4
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.12

### Client Setup Information

Webapp.
Latest Google Chrome (Version 83.0.4103.61)

### Relevant logs:
No relevant server logs when going to Administration -> View Logs

No relevant browser logs in inspect element.

**Comment by johnypeterson** [comment]
This should be reopened. The problem still exists

**Comment by mrmookie** [comment]
Same issue here on latest SNAP
