### ISSUE TITLE
incomplete german translation

### ISSUE THREAD

**Issue by LarsImNetz** [RocketChat/Rocket.Chat.Livechat#446]
Hi,
Found out there are some not translated values in file: Rocket.Chat.Livechat/src/i18n/de.json
and one typo.

"insert_your_field_here_d631e875": "Insert your %{field} here...",
could be translated to "Hier %{field} eintragen..."
So it works with 'Name' and 'Email' in the right way.

"invalid_email_e82f3682": "Invalid email",
could be translated to "Email ist ungültig"

"invalid_value_12ca12c2": "Invalid value",
could be translated to "Wert ist ungültig"

 "waiting_queue_800061da": "Waiting queue...",
could be translated to "Bitte warten..."

"your_spot_is_spot_a35cd288": "Your spot is #%{spot}",
could be translated to "Sie stehen an %{spot}. Stelle"

"your_spot_is_spot_estimated_wait_time_estimatedwai_d0ff46e0": "Your spot is #%{spot} (Estimated wait time: %{estimatedWaitTime})"

could be translated to: "Sie stehen an %{spot}. Stelle (Geschätzte Wartezeit: %{estimatedWaitTime})"

Typo:
"one": "Eine neue Nachrict seit %{since}",
right: "Eine neue Nachricht seit %{since}"

regards.

**Comment by LarsImNetz** [comment]
Ups, one point in my suggestions: 

"waiting_queue_800061da": "Waiting queue...",
could be translated to "Warteschlange..."

**Comment by JLNNN** [comment]
@Rocket.Chat Team: Please see these pull requests:

- https://github.com/RocketChat/Rocket.Chat.Livechat/pull/447
- https://github.com/RocketChat/Rocket.Chat.Livechat/pull/448

**Comment by JLNNN** [comment]
@renatobecker this issue can be closed.

**Comment by LarsImNetz** [comment]
Yes, please close this issue.
