### ISSUE TITLE
Embed widget as part of page without float

### ISSUE THREAD

**Issue by hartois** [RocketChat/Rocket.Chat.Livechat#452]
Hi
Now I have
![image](https://user-images.githubusercontent.com/11641656/88131944-d1bd9280-cbe6-11ea-959d-1632ecb4d3a9.png)

But I want embed widget into page div, without float and hidding. Something like this:
![image](https://user-images.githubusercontent.com/11641656/88131979-eb5eda00-cbe6-11ea-8667-001524fd5498.png)

How can I do this?

**Comment by renatobecker** [comment]
Hi @hartois 

You just need to add the `mode=popout` to the livechat route:
`https://your-server-url/livechat?mode=popout`

**Comment by hartois** [comment]
I'm already tried this. But this does not help.

I'm use code:
```
<script type="text/javascript">
    (function(w, d, s, u) {
        w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
        var h = d.getElementById('app'), j = d.createElement(s);
        j.async = true; j.src = 'https://chat.examplecom/livechat/rocketchat-livechat.min.js?_=201903270000';
        h.appendChild(j);
    })(window, document, 'script', 'https://chat.example.com/livechat?mode=popout');
</script>
```
But rocketchat-widget DIV inserts into body instead of DIV with id="app" and have position:fixed style

![image](https://user-images.githubusercontent.com/11641656/88181517-a31bd800-cc37-11ea-9e47-93b5cf959ab8.png)

**Comment by renatobecker** [comment]
> I'm already tried this. But this does not help.
> 
> I'm use code:
> 
> ```
> <script type="text/javascript">
>     (function(w, d, s, u) {
>         w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
>         var h = d.getElementById('app'), j = d.createElement(s);
>         j.async = true; j.src = 'https://chat.examplecom/livechat/rocketchat-livechat.min.js?_=201903270000';
>         h.appendChild(j);
>     })(window, document, 'script', 'https://chat.example.com/livechat?mode=popout');
> </script>
> ```
> 
> But rocketchat-widget DIV inserts into body instead of DIV with id="app" and have position:fixed style
> 
> ![image](https://user-images.githubusercontent.com/11641656/88181517-a31bd800-cc37-11ea-9e47-93b5cf959ab8.png)

It won't work because you're adding the parameter into the Livechat script instead of creating a new HTML element(such as an iframe) where the livechat will be displayed.
If you don't want to use the Livechat as a widget, you need to get the livechat from the route and display it on your own, this is how it works.

**Comment by hartois** [comment]
I also trying create own iframe with src="https://chat.example.com/livechat?mode=popout"
But in this case Widget API does not work. How can I customize interface, set department?

**Comment by hartois** [comment]
I solved the problem by build own rocketchat-livechat.js with the necessary changes
