### ISSUE TITLE
Operator's prepared messages

### ISSUE THREAD

**Issue by hartois** [RocketChat/Rocket.Chat.Livechat#453]
There is a need for prepared messages that the operator can select and send to the visitor. For example "Good afternoon. How can I help?" or "Do you still have questions?"

Is there such a possibility?

**Comment by renatobecker** [comment]
I think this is what you're looking for https://www.youtube.com/watch?v=-bC-ZVAj9pc
If so, the `Canned Responses` feature is available on our `Enterprise Edition`.

Also, for this kind of question, please, use our forum.

Thanks.

**Comment by hartois** [comment]
Thanks
