### ISSUE TITLE
Custom Fields in Live Chat

### ISSUE THREAD

**Issue by aliciamarianne1507** [RocketChat/Rocket.Chat.Livechat#462]
Hi, i would like to know if is possible change the apparance of custom fields, they're showing like this:

![image](https://user-images.githubusercontent.com/57607749/89337171-ed0db080-d670-11ea-961a-1b3b9a94a275.png)

**Comment by renatobecker** [comment]
> Hi, i would like to know if is possible change the apparance of custom fields, they're showing like this:
> 
> ![image](https://user-images.githubusercontent.com/57607749/89337171-ed0db080-d670-11ea-961a-1b3b9a94a275.png)

What's your server version?
The appearance of the custom fields have changed, they look like this, currently:

![Screen Shot 2020-08-06 at 11 06 48](https://user-images.githubusercontent.com/59577424/89541765-2bbc7b80-d7d5-11ea-9fad-a591302502b8.png)

**Comment by aliciamarianne1507** [comment]
@renatobecker I managed to make the modification, it was the version of the app. Thanks
