### ISSUE TITLE
Add button component Quick-reply / action button support

### ISSUE THREAD

**Issue by engahmed1190** [RocketChat/Rocket.Chat.Livechat#466]
I have checked the old open issue but found that they are closed, can you update me how we can send action button using Live Chat.

#408 
#437

**Comment by engahmed1190** [comment]
@murtaza98  can you please share with me your last findings

**Comment by renatobecker** [comment]
We are working on new `Rich Message Components`, the `quick reply` buttons are part of it.
The plan is to have them in place on the next release.

**Comment by serjk** [comment]
Hi @guimaraesdiego 
Seems to me not full support. I've tested buttons feature on the latest widget code base. It has not been implemented yet. 
I used a button message example. 
` "attachments": [{
                "title": "text button with msg in chat window",
                "actions": [{
                    "type": "button",
                    "text": "Say hello in chat window?",
                    "msg": "hello in chat window",
                    "msg_in_chat_window": true
                }]
            }]`
@renatobecker Is any update about buttons feature implementation?
