### ISSUE TITLE
Widget is not displaying if none of the agents is active

### ISSUE THREAD

**Issue by ashwaniYDV** [RocketChat/Rocket.Chat.Livechat#469]
Console error is shown below:
![Screenshot from 2020-08-12 21-08-35](https://user-images.githubusercontent.com/43786728/90044379-330aea00-dceb-11ea-9d42-f7c87985934f.png)

**Comment by renatobecker** [comment]
@ashwaniYDV which branch are you running?

**Comment by ashwaniYDV** [comment]
> @ashwaniYDV which branch are you running?

On the develop branch.
