### ISSUE TITLE
Unable to send an offline message in the Livechat (button disabled) - was working in 3.5.4

### ISSUE THREAD

**Issue by echantigny** [RocketChat/Rocket.Chat.Livechat#494]
### Description:

I have a Livechat widget in a webpage which works fine.  Out of business hours, the Leave a message box shows up to let you enter a name, email and message, but no matter what I do, the send button is greyed out and disabled.  

### Steps to reproduce:

1. Enable Omnichanned
2. Enable business hours and make it so the hours today are out of your current range
3. Get the Javascript widget in a webpage
4. When you try to fill in the Leave a message box, you can't because the button is disabled

### Expected behavior:

When the required fields are filled, the button should be enabled.

### Actual behavior:

The button stays disabled

### Server Setup Information:

- Version of Rocket.Chat Server:  3.6.0
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version:  Chrome Version 85.0.4183.83 (Official Build) (64-bit)
- Operating System: Windows 10

**Comment by echantigny** [comment]
I just went back to the 3.5.4 version to see if it was an issue then, and it wasn't.  This issue is introduced in the 3.6.0 version.

**Comment by unsnapp8** [comment]
Also running into this issue

**Comment by echantigny** [comment]
@renatobecker Any ETA on a fix for this?  It's kind of a big deal, especially since it got broken in the 3.6 update.

**Comment by renatobecker** [comment]
This fix is coming out with the new Rocket.Chat release, `3.7`,  which is going to be available by the end of today.

**Comment by echantigny** [comment]
@renatobecker 3.7 is up and running and this is still not fixed.

**Comment by renatobecker** [comment]
> @renatobecker 3.7 is up and running and this is still not fixed.
> 
> edit: Ok, sorry, it is actually working. The issue now is that you are validating the email, but you are not letting the user know that the email address is wrong. The only indicator is that they can't click the Send button.
> 
> another edit: To clarify, you are checking if the email is "possible" to show the send button. If it is possible (a full email address), you show the button and THEN validate the actual email address.
> 
> I see 2 options here:
> 
> 1. Show the send button no matter what and validate when clicked.
> 2. Show a warning on blur if the email address is impossible

I got it.
Feel free to create a new **feature request** issue describing your requirements.

Also, I think we can close this issue, right?

**Comment by echantigny** [comment]
@renatobecker Yes, I think this is resolved.  The other part is a UX issue that was already present in older versions.  I will create a new Feature Request soon.
