### ISSUE TITLE
Rename "Departments" text on menu and header?

### ISSUE THREAD

**Issue by carlo-fontanos** [RocketChat/Rocket.Chat.Livechat#512]
Hi, we would like to change the text here: 

![image](https://user-images.githubusercontent.com/12164593/96220223-ebd6f900-0fba-11eb-8ed7-53f2e767049b.png)

Is it possible? 

Thanks,
Carl

**Comment by renatobecker** [comment]
Hi,

Please, use the correct channel to ask this kind of question -> https://open.rocket.chat/channel/omnichannel
Thanks.

**Comment by carlo-fontanos** [comment]
Hello @renatobecker I believe I am in the correct channel for this question. If you check the attached image to my question, specifically the URL bar, you will see that I am in the `/livechat-manager/departments `. If this is not the correct channel for this channel, then please advice.
