### ISSUE TITLE
[Question] What about not-only Livechat?

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat.Livechat#52]
Rocket.Chat.Livechat project looks promising but what if I'll want to use it to no-livechat integration somewhere? 

I know that primary target is Livechat but this client looks so awesome it would be useful to other integrations - to be used like standard-web version but more programatically customisable to embed somewhere else for example.

**Comment by ggazzo** [comment]
hey @piotrkochan, actually this project will never be a rocketchat client, but you will be able to import ours components/screens and write your own logic...AND more we are rewrite the rocketchat based on this client, I cant promise or say deadlines, but we are building this livechat to inspire the new client ;)
