### ISSUE TITLE
Link https://rocket.chat/Rocket.Chat.Livechat Gives 404 Error

### ISSUE THREAD

**Issue by saideepesh000** [RocketChat/Rocket.Chat.Livechat#527]
At the moment the link in the About section of the repo gives a 404 Page not found an error

**Comment by renatobecker** [comment]
I didn't get it.
What's this link supposed to do?

**Comment by saideepesh000** [comment]
> 
> 
> I didn't get it.
> What's this link supposed to do?

I don't know about the link, but it is in the About section of the repository, under the "insights" tab.

**Comment by Ein-Tim** [comment]
@renatobecker The link still gives a 404, will you fix this?

**Comment by dudanogueira** [comment]
link changed! thanks for pointing out!
