### ISSUE TITLE
Live chat widget unresponsive after pop out mode

### ISSUE THREAD

**Issue by mfahad19** [RocketChat/Rocket.Chat.Livechat#532]
### Description:

After expanding the live chat widget and then closing the pop out window. The live chat icon is available on the page but is not responsive. Open incognito window and it works, pop out window there and close it and stops working there as well.

### Steps to reproduce:

1. Live chat page, open live chat widget
2. Click on expand chat
3. close the popped out window
4. Now click on live chat widget icon

### Expected behavior:

It should open the chat widget

### Actual behavior:

Nothing happens on clicking the live chat icon/button.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Ubuntu 20.04
- Deployment Method: manual install
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Desktop/Chrome 86.0.4240.111
- Operating System: Windows7 & Windows 10

**Comment by renatobecker** [comment]
Closed -> https://github.com/RocketChat/Rocket.Chat.Livechat/pull/529.

**Comment by mjunghanns** [comment]
I had the same issue as described here: [https://github.com/RocketChat/Rocket.Chat/issues/19603](https://github.com/RocketChat/Rocket.Chat/issues/19603).

**Comment by renatobecker** [comment]
> I had the same issue as described here: [RocketChat/Rocket.Chat#19603](https://github.com/RocketChat/Rocket.Chat/issues/19603).

The fix for the issue came out with Rocket.Chat release `3.8`.

**Comment by Corinari** [comment]
@renatobecker it seems that there was an error with publishing it, looks like V3.7.2 was released in the 3.8 Tag
See Server details of my Testing environment below. 
![Rocketchat3 7 2](https://user-images.githubusercontent.com/70264718/99687006-744a2d00-2a84-11eb-8cc9-1e0da4dc55b9.png)

**Comment by Corinari** [comment]
[https://github.com/RocketChat/Rocket.Chat/issues/19553](Issue)
