### ISSUE TITLE
Mixed Content error with only https being used

### ISSUE THREAD

**Issue by jwalker5006** [RocketChat/Rocket.Chat.Livechat#548]
Pop up panel not fully rendering due to mixed content error. parent page is https, javascript references only http but javascript pushing http.

the site hosting RocketChat livechat javascript is https://subdomain.ourdomain.com 

Server build is 3.9.3

1. RocketChat site running https and reverse proxy
2. Live Chat set to use https
3. But when the live chat loads, I get a partial rendering (See image) and looking at inspect I get the following error

![image](https://user-images.githubusercontent.com/6217843/105092748-46bf3700-5a67-11eb-9f1d-b55739dfb324.png)

### Console Error
Mixed Content: The page at 'https://www.ourdomain.com/' was loaded over HTTPS, but requested an insecure resource 'http://rc.ourdomain.com/api/v1/livechat/config?token=bunchofrandomstuff'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ VM823:formatted:44

### Javascript used
```
        <script type="text/javascript">
            (function (w, d, s, u) {
                w.RocketChat = function (c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
                var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
                j.async = true; j.src = 'https://rc.ourdomain.com/livechat/rocketchat-livechat.min.js?_=201903270000';
                h.parentNode.insertBefore(j, h);
            })(window, document, 'script', 'https://rc.ourdomain.com/livechat');
        </script>
```

I have been digging through rocketchat source code but cannot find out what in the code is trying to render http content

_Originally posted by @jwalker5006 in https://github.com/RocketChat/Rocket.Chat.Livechat/issues/250#issuecomment-763140483_

**Comment by Swayamsvk** [comment]
Is this issue still active?

**Comment by jwalker5006** [comment]
I will close the issue. Upgrading to 3.11 seemed to fix the issue.
