### ISSUE TITLE
Unable to type messages in the livechat

### ISSUE THREAD

**Issue by asarubbo** [RocketChat/Rocket.Chat.Livechat#551]
This is how looks the livechat atm, I really don't know where to type to leave a message.

![Screenshot_20210205_143155](https://user-images.githubusercontent.com/4741819/107040064-01b53780-67bf-11eb-8b47-9db4e636e3d6.png)

Rocket.chat version 3.11.0

**Comment by APPX-Studio** [comment]
yes,i don't know.
 i have same issues.
i have install chat.server,
but i don't know connect this client.

**Comment by renatobecker** [comment]
The same case has already been reported by other community members:

https://github.com/RocketChat/Rocket.Chat.Livechat/issues/528#issuecomment-717906739

**Comment by asarubbo** [comment]
Hello @renatobecker

in our case, we had the rocket chat server available at: https://rocket.example.com:port/rocket. Since deploy on different path than / was not supported ( we had few bugs with that and someone from devs said that it is not supported ) we switched to https://rocket.example.com:port. and it started to not work after this change.

In the livechat settings menu, in the installation tab, it still reports the block of code with the old path instead of the new. Is there any place where this settings has been recorded and not updated?

Thanks

**Comment by asarubbo** [comment]
I don't know the reason but it worked again after a server machine reboot while it didn't work after the service restart.
