### ISSUE TITLE
bodyStyle variable (body.style attribute)

### ISSUE THREAD

**Issue by nop1984** [RocketChat/Rocket.Chat.Livechat#572]
It would be really nice if you init variable bodyStyle with = document.body.style somewhere earlier in widjet.js lifecycle before using it as undefined in updateWidgetStyle() to document.body. For example createWidget() seems to be nice place for initialization.
Thank you.

P.S. same issue https://forums.rocket.chat/t/livechat-script-omnichannel-removes-style-attribute-from-body/9940

**Comment by johncrisp** [comment]
Yes I have just replicated this on two sites

Set `<body style="background-color: red;">`
Put the Livechat widget just before `</body>`
The page will flash red then back to white.
Tag is set to:
`<body style="">`

**Comment by johncrisp** [comment]
I think this is related/same:

https://forums.rocket.chat/t/livechat-script-omnichannel-removes-style-attribute-from-body/9940/15

**Comment by nop1984** [comment]
Yes. Thanks @johncrisp . I am happy that this bug finally noticed and that my account and comment on forum.rocket.chat are unblocked.

**Comment by johncrisp** [comment]
And logged in Clickup too
