### ISSUE TITLE
links dont open in new tab

### ISSUE THREAD

**Issue by birne27** [RocketChat/Rocket.Chat.Livechat#603]
Hello Folks,

since the new Version 3.13.* all links posted by agents to an Omnichannel conversation dont open in a new tab.
There is no target="_blank" anymore inside the widget frame. Customers open up a clicked page inside the iframe, so its really inpractical now. 

Is there any setting in the Administration Panel to fix this?

Best Regards

**Comment by billynoah** [comment]
`target="_parent"` would be fine as well - better yet, a setting that allows admin to choose.

**Comment by ramonmolossi** [comment]
Probably the DomPurify is purging the "target" attribute.

The solution is to modify the MessageText/markdown.js:

`export const renderMarkdown = (...args) => sanitize(md.render(...args), { ADD_ATTR: ['target','rel'] });`

**Comment by billynoah** [comment]
Thanks @ramonmolossi, created a PR for this: https://github.com/RocketChat/Rocket.Chat.Livechat/pull/610

**Comment by MartinSchoeler** [comment]
Fixed by https://github.com/RocketChat/Rocket.Chat.Livechat/pull/610
