### ISSUE TITLE
LiveChat IME conversion not working for Japanese

### ISSUE THREAD

**Issue by sctEdwin** [RocketChat/Rocket.Chat.Livechat#605]
Hi there, I am referring to the fix for IME.
https://github.com/RocketChat/Rocket.Chat.Livechat/pull/559
Upon further testing, it seems when I tried to input the first word into the text box, depending on the speed of input,
sometimes IME conversion fail if I input fast.(This happens in both firefox and Chrome)
What could be possible reason and can you fix this? I run out of idea on how to fix this.
![ime_problem](https://user-images.githubusercontent.com/72842751/117762278-cc0f6700-b263-11eb-9c5f-4ce1e13d8527.gif)

I am not sure why Enter key is required for each ime conversion.
Normally space bar should works. It seems livechat does not treat space bar as ime conversion.

**Comment by MartinSchoeler** [comment]
Hey @sctEdwin Could you give us more info? I'm not that used with IME so:

- What is the condition for failing, the pop up not showing or the characters not being changed?
- Are you using an specific IME tool (I've tested with the google one)
- With the one tool I've tested, spacebar just jumped to the next item.

Thanks!

**Comment by sctEdwin** [comment]
@MartinSchoeler  Thank you for your reply.
>What is the condition for failing, the pop up not showing or the characters not being changed?
For example, if I input the following 5 Japanese hiragana characters(think of them like tokens)
こんにちは　(konnnichiha)
the sequence of input would, of course, in order as the following: (bracket are the keys that I actually type on key board)
1. こ (k,o)
2. ん (n,n)
3. に (n,i)
4. ち (c,h,i)
5. は (h,a)
6. space key or enter key

In a normal Japanese IME behaviour, these inputed characters(k,o,n,n,n,i,c,h,i,h,a) are not actually "confirmed" 
until I push "Space" key or "Enter" key.

However, here in RC Livechat after
say after inputting step 1(k, o)and step 2(n, n), i.e. こん,  in a state where I have to not yet "confirmed",
the IME "confirmed" automatically the input characters (k,o,n,n) which is undesired.

>Are you using an specific IME tool (I've tested with the google one)
I am just using the default Japanese IME tool that comes with Windows 10.(add a language in Windows settings)

>With the one tool I've tested, spacebar just jumped to the next item.
I am not sure what you mean by jump to the next item but it seems that it is the normal behavior.

Say if you press "Space" key (or "Enter" key), the characters that you have entered
will be converted to Japanese hiragana characters or Japanese kanji character or Japanese katakana character or remain as English alphabet character should there be  no conversion candidate for just combination.
Depending on your selection in the conversion candidate menu(through number or arrow keys).

See https://support.microsoft.com/en-us/windows/microsoft-japanese-ime-da40471d-6b91-4042-ae8b-713a96476916
for what it mean by conversion candidate menu.

Without delving too much into which candidate to select in the conversion candidate menu,
for example pick the default candidate in the conversion candidate menu, just press Enter:
e.g. k, o, Enter  => こ and you can start typing again from the insertion point  which should be behind こ.

The problem here is, the IME does not function the way as it is in Windows i.e. wait until I finish entering characaters,
after I pressed "Space" and only then display the conversion candidate menu. 
After I picked the candidate for conversion and press "Enter" key, only then should the insertion point appear.

**Comment by MartinSchoeler** [comment]
@sctEdwin Interesting, it seems to be an issue just with the windows IME tool. Will do some testing with a Windows 10 OS to see if I can find out the issue. Thanks for the extra details!

**Comment by MartinSchoeler** [comment]
@sctEdwin Could you help me test something out?

- Could you go to https://rocket.chat/ and test if the issue is in that widget?
- Could you send me a gif of the IME tool working properly?

I just need to confirm if I'm reproducing the issue correctly. Thanks!

**Comment by sctEdwin** [comment]
@MartinSchoeler 

>Could you go to https://rocket.chat/ and test if the issue is in that widget?
I tested the https://rocket.chat/  
but because live chat team is offline, I were unable to get to the exact text box as in the normal live chat conversation.

>Could you send me a gif of the IME tool working properly?
Below is a correct behavior of "こんにちは”(konichiha) + "Enter" Key + "こんにちは"(konichiha) + "Enter" key
which should display "こんにちはこんにちは" and 
you should be able to see conversion candidate menu poping up before each confirmation("Enter" key).

Notice there is not prior/automatic conversion until I press "Enter" key".
![correct behavior](https://user-images.githubusercontent.com/72842751/128790749-0208f3f2-4414-4087-9225-ca37bae41ff5.gif)
