### ISSUE TITLE
Wrong link in the About section of the repository

### ISSUE THREAD

**Issue by aayushsrivastava9760** [RocketChat/Rocket.Chat.Livechat#673]
The link given in the About section of the repository leads to 404 page
![WhatsApp Image 2022-01-05 at 01 48 00](https://user-images.githubusercontent.com/81965095/148118644-7d5fb9d2-0a1e-472d-9632-4e27e6c5a7b6.jpeg)
 

Kindly change the link from `https://rocket.chat/Rocket.Chat.Livechat` to `https://rocket.chat/`

**Comment by dudanogueira** [comment]
link changed! thanks for pointing out!
