### ISSUE TITLE
Can this be integrated into React Native project?

### ISSUE THREAD

**Issue by jmagdada** [RocketChat/Rocket.Chat.Livechat#81]
Hi, I'm sorry for the stupid question. I am new to React Native and I would like to add the rocket.chat liveChat into the existing RN project. Will this work with React Native?

**Comment by d-gubert** [comment]
Hi. I'm assuming it would be possible if you integrated it in a [WebView](https://github.com/react-native-community/react-native-webview), in which case you will probably have to host your LiveChat somewhere out there. 

@renatobecker @tassoevan what do you think?

**Comment by d-gubert** [comment]
Since this is not really an issue but a discussion/question, I'd suggest you to move it to our forums instead of GitHub :)

https://forums.rocket.chat/

Closing this issue for now

**Comment by jmagdada** [comment]
hi @d-gubert thank you for your response. I'll move this to the forum :)
